<div class="row-fluid">
    <div class="dialog">
        <div class="block">
            <p class="block-heading">Sign In</p>
            <div class="block-body">
                <form action="<?php echo SUB_URL?>/login" class="ajax-form" method="post">
                    <label>Username</label>
                    <input type="text" name="username" class="span12">
                    <label>Password</label>
                    <input type="password" name="password" class="span12">
                    <button type="submit" class="btn btn-primary pull-right">Sign In</button>
                    <label class="remember-me"><input type="checkbox" name="remember" value="1"> Remember me</label>
                    <div class="clearfix"></div>
                </form>
            </div>
        </div>
        
    </div>
</div>