
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="<?php echo BASE_URL ?>/public/style/css/block.css" />
        <link rel="stylesheet" href="<?php echo BASE_URL ?>/public/style/css/jquery-ui.css" />

        <script type="text/javascript" src="<?php echo BASE_URL . '/public/style/js/jquery-1.7.2.js' ?>"></script>
        <script type="text/javascript" src="<?php echo BASE_URL . '/public/style/js/script.js' ?>"></script>
        <script type="text/javascript" src="<?php echo BASE_URL . '/public/style/js/plugin.js' ?>"></script>
        <script type="text/javascript" src="<?php echo BASE_URL ?>/public/style/js/jquery-ui.min.js"></script>
        <script type="text/javascript" src="http://vnexpress.net/Service/Gold_Content.js"></script>
        <script type="text/javascript" src="http://vnexpress.net/Service/Forex_Content.js"></script>
        <script type="text/javascript"
                src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDSxPygO4ci1pr7_jvXkbmUu9G0J3lJk8Q&sensor=false">
        </script>

        <script type="text/javascript">
            function initialize() {
                var mapOptions = {
                    center: new google.maps.LatLng(-34.397, 150.644),
                    zoom: 8,
                    mapTypeId: google.maps.MapTypeId.ROADMAP
                };
                var map = new google.maps.Map(document.getElementById("map"),
                        mapOptions);
            }
            google.maps.event.addDomListener(window, 'load', initialize);
        </script>
        <style>
            #map{
                width:400px;
                height: 400px;
            }
        </style>
    </head>
    <body>
        <div id="map">

        </div>
    </body>
</html>