<?php $s = $this->slide?>
<form class="slide" action="<?php echo SUB_URL ?>/default/setting/editslide" method="post" enctype="multipart/form-data">
    <div class="form-content">
        <input type="hidden" name="ID" value="<?php echo $s['ID']?>"/>
        <label>Tiêu đề</label>
        <input type="text" value="<?php echo $s['title']?>" name="title" class="input-xlarge"/>
        <label>Tóm tắt</label>
        <input type="text" value="<?php echo $s['summary']?>" name="summary" class="input-xlarge"/>
        <label>Link đến bài viết</label>
        <input type="text" value="<?php echo $s['link']?>" name="link" class="input-xlarge"/>
        <label>Kích hoạt 
            <input type="checkbox" value="1" name="active" <?php echo $s['active'] == 1 ? "checked" : ""?>/></label>
        <input type="file" name="file" id="slide_file" />
        <button type="submit" class="btn btn-primary"><i class="icon-save"></i> Cập nhật</button>
        <button class="btn" onclick="delete_item('Xóa ảnh đã chọn', '<?php echo SUB_URL?>/default/setting/deleteslide?ID=<?php echo $s['ID']?>'); return false;"><i class="icon-remove"></i> Xóa ảnh</button>
    </div>
    <div class="img-content">
        <img class="img-polaroid" src="<?php echo BASE_URL?>/public/style/images/slide/<?php echo $s['image']?>" id="show_slide" name="myfile" width="120"/>
    </div>    
</form>


