<?php $slides = $this->slides ?>
<div id="msg_slideshow" class="msg_slideshow">
    <div id="msg_wrapper" class="msg_wrapper">
    </div>
    <div id="msg_controls" class="msg_controls"><!-- right has to animate to 15px, default -110px -->
       
        <a href="#" id="msg_prev" class="msg_prev"></a>
        <a href="#" id="msg_pause_play" class="msg_pause"></a><!-- has to change to msg_play if paused-->
        <a href="#" id="msg_next" class="msg_next"></a>
    </div>
    <div id="msg_thumbs" class="msg_thumbs"><!-- top has to animate to 0px, default -230px -->
        <div class="msg_thumb_wrapper">
            <?php foreach ($slides as $s):?>
            <a href="<?php echo $s['link']?>"><img src="<?php echo BASE_URL?>/public/style/images/slide/<?php echo $s['image']?>" alt="<?php echo BASE_URL?>/public/style/images/slide/<?php echo $s['image']?>"
             title="<?php echo $s['title']?>" /></a>
            <?php endforeach;?>
        </div>
       
        <span class="msg_loading"></span><!-- show when next thumb wrapper loading -->
    </div>
</div>
