<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Admin</title>

        <link href="<?php echo SUB_URL ?>/public/style/css/layout.css" type="text/css" rel="stylesheet"/>
        <link rel="stylesheet" type="text/css" href="<?php echo SUB_URL ?>/public/style/css/theme.css"/>
        <link href="<?php echo SUB_URL ?>/public/style/css/awsome.css" rel="stylesheet">
        <link rel="stylesheet" href="<?php echo SUB_URL ?>/public/style/css/jquery-ui.css" />
        <link rel="stylesheet" href="<?php echo SUB_URL ?>/public/style/css/owl.css" />
        <link rel="stylesheet" href="<?php echo SUB_URL ?>/public/style/css/bootstraps.css" />
        <script type="text/javascript" src="<?php echo SUB_URL . '/public/style/js/jquery-1.7.2.js' ?>"></script>
        <script type="text/javascript" src="<?php echo SUB_URL . '/public/style/js/script.js' ?>"></script>
        <script type="text/javascript" src="<?php echo SUB_URL . '/public/style/js/plugin.js' ?>"></script>
        <script type="text/javascript" src="<?php echo SUB_URL . '/public/style/js/component.js' ?>"></script>
        <script type="text/javascript" src="<?php echo SUB_URL ?>/public/style/js/jquery-ui.js"></script>
        <script type="text/javascript" src="<?php echo SUB_URL ?>/public/style/js/jquery.livequery.min.js"></script>
        <!-- Demo page code -->

    </head>

    <body > 

        <div class="navbar">
            <div class="navbar-inner">
                <a class="brand" href="<?php echo BASE_URL ?>"><span class="first">Admin Panel</span> <span class="second">Camdosim.vn</span></a>
            </div>
        </div>

        <div id="main-content">
            <?php echo $this->layout()->content; ?>
        </div>

    </body>
</html>



