<div class="header">
    <h1 class="page-title">Sửa dịch vụ</h1>
</div>

<ul class="breadcrumb">
    <li><a href="<?php echo SUB_URL ?>" >Trang chủ</a> <span class="divider">/</span></li>
    <li><a href="service/index" onclick="call_ajax_load_content(this, 'Dịch vụ');
            return false;" >Dịch vụ</a> <span class="divider">/</span></li>
    <li class="active">Sửa dịch vụ</li>
</ul>

<div class="container-fluid">
    <div class="row-fluid">
        <?php
        $p = $this->post;
        if ($this->error):
            ?>
            <div class="alert alert-error">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <?php echo $this->error ?>
            </div>
        <?php endif; ?>
        <form id="form-content" action="<?php echo SUB_URL ?>/service/index/edit" method="post" enctype="multipart/form-data">
            <?php
            $categories = $this->categories;
            ?>
            <input type="hidden" name="ID" value="<?php echo $p['ID']?>"/>
            <label>Tên dịch vụ <span class="required">(*)</span></label>
            <input type="text" name="title" value="<?php echo $p['title']?>" class="input-xlarge"/>
            <label>Tóm tắt <span class="required">(*)</span><span class="sub">(Thông tin tóm lược hiển thị trong danh sách)</span></label>
            <input type="text" name="summary" value="<?php echo $p['summary']?>" class="input-xlarge"/>
            <label>Nhóm dịch vụ <span class="required">(*)</span></label>
            <select name="category_id" class="input-xlarge">
                <option value="">Chọn nhóm dịch vụ</option>
                <?php foreach ($categories as $c): ?>
                <option value="<?php echo $c['ID'] ?>" <?php echo $c['ID'] == $p['category_id'] ? "selected" : ""?>><?php echo $c['title'] ?></option>
                    <?php
                endforeach;
                ;
                ?>
            </select>
            <?php $id = uniqid(); ?>
            <label>Ảnh đại diện</label>
            <img src="<?php echo BASE_URL?>/upload/service/<?php echo $p['thumb']?>" id="<?php echo $id ?>_show" width="120"/>
            <input type="file" name="thumb" value="" id="<?php echo $id ?>" class="input-xlarge"/>
            
            <label>Keywords</label>
            <input type="text" name="keywords" value="<?php echo $p['keywords']?>"  class="input-xlarge"/>
            <label>Nội dung</label>
            <textarea name="desc"><?php echo $p['desc']?></textarea>

            <div style="margin-top: 15px">
                <button type="submit" class="btn btn-primary"><i class="icon-save"></i> Cập nhật</button>
                <button type="reset" class="btn"><i class="icon-refresh"></i> Hủy bỏ</button>
            </div>
        </form>   
    </div>
</div>
<script type="text/javascript">
        (function($) {
            $(document).ready(function() {
                upload_img('<?php echo $id ?>', '<?php echo $id ?>_show', '<?php echo $id ?>_path');
                var editor = CKEDITOR.replace('desc', {
                    height: 400
                });
                CKFinder.setupCKEditor(editor, baseURL + '/public/style/ckeditor/ckfinder/');
            });
        })(jQuery);
</script>
