<?php $users = $this->users; ?>
<a href="<?php echo BASE_URL . "/user/index/add" ?>">Add new</a>
<form action="<?php echo BASE_URL . "/user/index/delete" ?>" class="ajax-form" method="post">
    <table>
        <tr>
            <th><input type="checkbox" id="ck_all" onchange="check_and_uncheck_all(this.id)"/></th>
            <th>STT</th>
            <th>ID</th>
            <th>Username</th>
            <th>Password</th>
            <th>Action</th>
        </tr>
        <?php
        foreach ($users as $k => $u):
            ?>
            <tr>
                <td align="center"><input type="checkbox" value="<?php echo $u['ID'] ?>" name="ID[]" class="ck_all_item"/></td>
                <td><?php echo ($k + 1) ?></td>
                <td><?php echo $u['ID'] ?></td>
                <td><?php echo $u['username'] ?></td>
                <td><?php echo $u['password'] ?></td>
                <td><a href="#" onclick="confirmDialog('Do you want to delete this user??',function(){parent.location.href='<?php echo BASE_URL?>/user/index/delete?ID=<?php echo $u['ID']?>'})">Delete</a> - 
                    <a href="#" onclick="show_dialog('Edit User', '', '<?php echo BASE_URL?>/user/index/edit?ID=<?php echo $u['ID']?>')">Edit</a></td>

            </tr>
            <?php
        endforeach;
        ?>
    </table>
    <input type="submit" value="delete all"/>
    
</form>
