<div class="header">
    <div class="stats">
        <p class="stat"><span class="number"><?php echo date('d/m/Y') ?></span>Ngày</p>
        <p class="stat"><span class="number">27</span>Tổng số truy cập</p>
        <p class="stat"><span class="number">53</span>Đang Online</p>
    </div>

    <h1 class="page-title">Trang chủ</h1>
</div>

<ul class="breadcrumb">
    <li><a href="index.html">Trang chủ</a></li>
</ul>

<div class="container-fluid">
    <div class="row-fluid">


        <div class="row-fluid">

            <div class="alert alert-info">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <strong>Just a quick note:</strong> Hope you like the theme!
            </div>
        </div>

        <!--                    <div class="row-fluid">
                                <div class="block span6">
                                    <a href="#tablewidget" class="block-heading" data-toggle="collapse">Users<span class="label label-warning">+10</span></a>
                                    <div id="tablewidget" class="block-body collapse in">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th>First Name</th>
                                                    <th>Last Name</th>
                                                    <th>Username</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td>Mark</td>
                                                    <td>Tompson</td>
                                                    <td>the_mark7</td>
                                                </tr>
                                                <tr>
                                                    <td>Ashley</td>
                                                    <td>Jacobs</td>
                                                    <td>ash11927</td>
                                                </tr>
                                                <tr>
                                                    <td>Audrey</td>
                                                    <td>Ann</td>
                                                    <td>audann84</td>
                                                </tr>
                                                <tr>
                                                    <td>John</td>
                                                    <td>Robinson</td>
                                                    <td>jr5527</td>
                                                </tr>
                                                <tr>
                                                    <td>Aaron</td>
                                                    <td>Butler</td>
                                                    <td>aaron_butler</td>
                                                </tr>
                                                <tr>
                                                    <td>Chris</td>
                                                    <td>Albert</td>
                                                    <td>cab79</td>
                                                </tr>
                                            </tbody>
                                        </table>
                                        <p><a href="users.html">More...</a></p>
                                    </div>
                                </div>
                                <div class="block span6">
                                    <a href="#widget1container" class="block-heading" data-toggle="collapse">Collapsible </a>
                                    <div id="widget1container" class="block-body collapse in">
                                        <h2>Here's a Tip</h2>
                                        <p>This template was developed with <a href="http://middlemanapp.com/" target="_blank">Middleman</a> and includes .erb layouts and views.</p>
                                        <p>All of the views you see here (sign in, sign up, users, etc) are already split up so you don't have to waste your time doing it yourself!</p>
                                        <p>The layout.erb file includes the header, footer, and side navigation and all of the views are broken out into their own files.</p>
                                        <p>If you aren't using Ruby, there is also a set of plain HTML files for each page, just like you would expect.</p>
                                    </div>
                                </div>
                            </div>-->

        <div class="row-fluid">
            <div class="block span6">
                <div class="block-heading">
                    <a href="#widget2container" data-toggle="collapse">Liên hệ mới</a>
                </div>
                <div id="widget2container" class="block-body collapse in">
                    <table class="table list">
                        <tbody>
                            <?php $messages = $this->messages; ?>
                            <?php foreach ($messages as $m):?>              
                            <tr>
                                <td>
                                    <p><i class="icon-user"></i> <?php echo $m['name'] ?></p>
                                </td>
                                <td>
                                    <p><?php echo short_title($m['title'], 150) ?></p>
                                </td>
                                <td>
                                    <p>Ngày tạo: <?php echo show_date($m['date_created']) ?></p>
                                    <a href="javascript:;" onclick="show_dialog('Chi tiết', '', baseURL + '/contact/index/view?ID=<?php echo $m['ID']?>')">
                                        Chi tiết
                                    </a> 
                                </td>
                            </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="block span6">
                <p class="block-heading">Not Collapsible</p>
                <div class="block-body">
                    <h2>Built with Less</h2>
                    <p>The CSS is built with Less. There is a compiled version included if you prefer plain CSS.</p>
                    <p>Fava bean jícama seakale beetroot courgette shallot amaranth pea garbanzo carrot radicchio peanut leek pea sprouts arugula brussels sprout green bean. Spring onion broccoli chicory shallot winter purslane pumpkin gumbo cabbage squash beet greens lettuce celery. Gram zucchini swiss chard mustard burdock radish brussels sprout groundnut. Asparagus horseradish beet greens broccoli brussels.</p>
                    <p><a class="btn btn-primary btn-large">Learn more &raquo;</a></p>
                </div>
            </div>
        </div>



        <footer>
            <hr>

            <!-- Purchase a site license to remove this link from the footer: http://www.portnine.com/bootstrap-themes -->
            <p class="pull-right">A <a href="http://www.portnine.com/bootstrap-themes" target="_blank">Free Bootstrap Theme</a> by <a href="http://www.portnine.com" target="_blank">Portnine</a></p>

            <p>&copy; 2012 <a href="http://www.portnine.com" target="_blank">Portnine</a></p>
        </footer>

    </div>
</div>